### ISSUE TITLE
Companion Login

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#1]
As a companion, I would like to be able to log in to the app so that I can see my list of clients.

**Comment by nelsonic** [comment]
@katbow our understanding is that AgeUK are already using Atlassian Crowd and want us to integrate with it. see: https://developer.atlassian.com/display/CROWDDEV/Crowd+REST+APIs

**Comment by andrewMacmurray** [comment]
@nelsonic we were debating whether to leave integrating with Atalssian Crowd for a later sprint, get the shell of the app working first

**Comment by andrewMacmurray** [comment]
@nelsonic we're gonna do some research on this and see how straight forward it is to integrate

**Comment by iteles** [comment]
First pass of this is complete. We'll need to add in a more detailed login functionality hooked up to permissions and clients in future sprints.
