### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#12]
Start thinking about what we need to use for this project

Some initial thoughts:

**backend:**
+ Obviously Hapi
+ Handlebars
+ Postgres

**Testing:**

+ Tape (standard)
+ Mocha & Chai (richer assertion library, nicer terminal output)
+ Jasmine (great for mocking up DOM for frontend testing)

**Frontend:**

+ Skeleton CSS (very lightweight and unobtrusive)
+ Semantic UI (potentially quicker to get UI components up and running)
+ Service workers??? - controversial, needs discussion

**Comment by andrewMacmurray** [comment]
After discussion:

**backend**

+ Hapi
+ Hapi Login
+ Handlebars
+ Postgres

**Testing**

+ Mocha & Chai (for backend)
+ Jasmine (for frontend)

**Frontend**

+ Skeleton CSS

**Comment by iteles** [comment]
@andrewMacmurray Thought you were going with tape for testing?

**Comment by andrewMacmurray** [comment]
@iteles we could do tape instead

**Comment by nelsonic** [comment]
Also, I think AgeUK are keen to use MySQL as they already have apps that use MySQL ...

**Comment by andrewMacmurray** [comment]
@nelsonic sure we could use that instead of postgres

**Comment by katbow** [comment]
Moved this info to the [wiki tech choices section](https://github.com/ageuk/companion-app/wiki/Tech-Choices)!
