### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#15]
+ [x] circle ci
+ [x] istanbul
+ [x] testing
+ [x] mysql install/setup 
+ [x] SASS
+ [x] linter (we're using semistandard!)

**Comment by iteles** [comment]
@katbow We're still waiting to find out whether the code will be open sourced, but if not, we should use circle ci as it's free for private repos.

@jrans @naazy and @conorc1000 are all using postgres in their projects so could give you a hand if you get stuck!

**Comment by andrewMacmurray** [comment]
@iteles @nelsonic suggested we use MySQL as AgeUK uses it for a number of their projects, do you think that would be ok?

**Comment by iteles** [comment]
Oh yes, of course, hadn't read the latest on https://github.com/ageuk/companion-app/issues/12 😊

**Comment by katbow** [comment]
@iteles should I go ahead with setting up circle ci instead of travis in case this becomes a private repo?

**Comment by iteles** [comment]
@katbow Sounds like a plan 👍

**Comment by katbow** [comment]
cool, thanks for the link!

**Comment by katbow** [comment]
Oops hit close and comment by accident there heh. Definitely not done yet!

**Comment by iteles** [comment]
Also, we will need a linter! (sorry I threw this into the mix pretty late on!)

**Comment by katbow** [comment]
@andrewMacmurray p.s. for the linter, you can still use the atom packages standard-formatter and linter-js-standard it can be adjusted in the settings for semistandard!

**Comment by nelsonic** [comment]
@katbow we're using https://github.com/Flet/semistandard/ in SciMu. 
see: https://github.com/TheScienceMuseum/collectionsonline/blob/11391dd406cdb7f3c8cff995df8772fb3e702aa6/package.json#L42 & https://github.com/TheScienceMuseum/collectionsonline/blob/11391dd406cdb7f3c8cff995df8772fb3e702aa6/package.json#L53

**Comment by katbow** [comment]
@nelsonic that's actually where me and @andrewMacmurray saw that :smile: I put it as part of the general test script but might be better if I split it up instead

**Comment by andrewMacmurray** [comment]
Closing as completed setup
Link to our tech choices: https://github.com/ageuk/companion-app/wiki/Tech-Choices
