### ISSUE TITLE
Decide on db structure

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#16]
Need to decide what tables are necessary and which columns should be in each table. #11

**Comment by iteles** [comment]
One to discuss with @rjmk in some detail on Monday.

**Comment by rjmk** [comment]
I may be coming in on Tuesday instead if this will work for people.

Whether or not that works, we should definitely make sure some requirements / details of the data storage are written up / linked to *before* we have this discussion -- it's something that really needs at least one night to sleep on

**Comment by katbow** [comment]
closed, see structure [here](https://github.com/ageuk/companion-app/wiki/Data-Structure)
