### ISSUE TITLE
Handlebars offline

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#18]
@rjmk we were thinking about how we might go about using handlebars for offline files, there's a precompiler: http://handlebarsjs.com/precompilation.html

but wondering if we're going to run into problems if we need to update our data dynamically. Do you have any thoughts?

**Comment by rjmk** [comment]
* Companion selecting a client and effects on the templates

**Comment by andrewMacmurray** [comment]
A thread about precompiling using Hapi

https://github.com/hapijs/hapi/issues/1816
