### ISSUE TITLE
Topics for Rafe

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#19]
- [x] Discuss db structure #11 #16 
- [x] Discuss best options for making the app work offline #18 #9 . 
    - [x] Storing the app shell - being able to access necessary files, go through app flow offline, etc
    - [x] Updating the app shell - anything to keep in mind for this as we're building? Using handlebars with local storage??
   - [ ] Storing + encrypting client data in local storage 
   - [ ] Accessing local storage data when connected to internet and putting in db

**Comment by nelsonic** [comment]
@katbow / @andrewMacmurray as discussed today, the _initial_ plan is to use a `cache manifest file` http://caniuse.com/#feat=offline-apps which is supported by _all_ the browsers (_despite being "deprecated" in https://html.spec.whatwg.org/multipage/browsers.html#offline ..._) and to _explain_ to Richard why we can't use Service Workers http://caniuse.com/#feat=serviceworkers _yet_.

**Comment by andrewMacmurray** [comment]
thanks @nelsonic we've updated the wiki and sent Richard an email detailing our decisions (we'll make sure we get a reply when he gets back from holiday)

**Comment by katbow** [comment]
Closing as we have all the info we need from this for sprint 1. Additional info to consider for later sprints is included in #68
