### ISSUE TITLE
Change actions in Action Plan to 'Completed'

### ISSUE THREAD

**Issue by asmaasehli** [ageuk/companion-app#26]
I would like to be able to change the actions within the Action plan to 'Completed', so that I know this is a finished task. I would also like to be able to reverse this should I need to (revert back to an 'Action' as not competed). I would like this to be date-stamped and viewable throughout my conversation with the client, as this helps me to keep track of the actions completed (and when), as well as those still outstanding.

**Comment by katbow** [comment]
Note for this one: we currently have this being stored in the MySQL database/localStorage as false to start. We need add in something (i.e. button) on the action plan page to toggle between completed or not.  This would update with the MySQL functions we already have as well.

**Comment by andrewMacmurray** [comment]
closed with pr #106
