### ISSUE TITLE
Action Plan items

### ISSUE THREAD

**Issue by asmaasehli** [ageuk/companion-app#27]
I would like the Action Plan to include the following items:

- [x] The action itself
- [x] The date the action(s) was/were created - priority-2
- [x] The status of the action (completed or todo)
- [x] The responsibility of who need to complete this action (Client vs Age UK) - priority-3

**Comment by katbow** [comment]
Note for fourth item: the 'completed by' is appended to the page, however it is default to AgeUK and can't currently be toggled. The function exists to update it in the MySQL database, however we need to be able to toggle it through the ui.

**Comment by andrewMacmurray** [comment]
closed with pr #106
