### ISSUE TITLE
Questions for wireframes meeting

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#35]
* What are the 2 buttons/logos to the left of the text at the top of the page? 
* Does the companion get to the list of actions by clicking on the blue circle saying the number of actions?
* For the page with the list of actions, what does add action do? Our understanding was that actions were only added by selecting them from the topic-prompt-action tree.
* On the actions to-do in the section that says who is responsible for completing the action, is this a slider which can be switched between ageuk and the client, or is this information input at a different time?
* How will topics/prompts/actions be edited for future sprints?

**Comment by katbow** [comment]
purple is for the section you are in, blue is for everything else (i.e if you are on the action to-do list page, then the round action button should be purple, all others should be blue).

Add action button on the action to-do list will be added to the backlog as not in the original scope. 

default is ageuk for action to-do list toggle button.

**Comment by iteles** [comment]
Closing, here for reference if needed.
