### ISSUE TITLE
Investigate waffle.io

### ISSUE THREAD

**Issue by iteles** [ageuk/companion-app#37]
Investigate the use of waffle.io as @asmaasehli was feeling the lack of prioritisation coming in from the *detailed* world of Jira

**Comment by andrewMacmurray** [comment]
OK will look into this tomorrow

**Comment by iteles** [comment]
@andrewMacmurray Not urgent! Let's get going on our scope and dig into this when we have some breathing room.

**Comment by iteles** [comment]
Closing as we worked well using Github alone these last few sprints 😊
