### ISSUE TITLE
Run through of offline handlebars options

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#44]
We were looking in to more detail into taking the app offline with handlebars #18. Most information we found was that we could precompile the templates or have the full handlebars library cached on the front end. 

The pro for precompiling is that it has better performance, however it involves several files that need to be cached and then we use the precompiled code to create the HTML. We're wondering if perhaps going this route is premature optimisation since it is only meant for ~12 users.

The full cached handlebars library would allow us to use handlebars essentially how we would normally (simpler), however we thought this would not be as good performance wise.

We wondering if @nelsonic or @rjmk have advice on how best to do this. Are we barking up the wrong tree :deciduous_tree: with either route?

We're just finishing off some handlebars set up we've working on today, and we'll push it up by end of day.

**Comment by rjmk** [comment]
I think you're right that it's premature optimisation. Not that this is a bad optimisation or one that we won't need this optimisation, but just that we should use it if we realise we need it
