### ISSUE TITLE
spike for handlebars precompilation

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#45]
Find more info about precompiling handlebars templates. #18 #44

**Comment by andrewMacmurray** [comment]
We've done a bit of research on this and this could be a neat solution:
https://www.npmjs.com/package/browserify-handlebars

Seeing as we're using browserify for testing this would fit nicely. It let's you require templates as precompiled functions, so you only need the handlebars runtime on the front end (much smaller and faster to load / render)
