### ISSUE TITLE
Reduce duplication in handlers & views

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#48]

**Comment by nelsonic** [comment]
@katbow usually a good idea to give specific examples of the duplication (link to lines of code with commit hash) so everyone can assess how "bad" the duplication is.

**Comment by katbow** [comment]
@nelsonic good point! 

Here's some of the files with duplication:
https://github.com/ageuk/companion-app/blob/master/lib/routes/login.js  
https://github.com/ageuk/companion-app/blob/master/lib/routes/clientlist.js  
https://github.com/ageuk/companion-app/blob/master/lib/routes/addclient.js

https://github.com/ageuk/companion-app/blob/master/public/views/login.html  
https://github.com/ageuk/companion-app/blob/master/public/views/clientlist.html  
https://github.com/ageuk/companion-app/blob/master/public/views/addclient.html

The duplication for the views and routes is related, so hopefully once we can fix one it'll help work out the other! We were thinking it's good to see this duplication so we can make the right abstractions later.
