### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#51]
might be worth setting up a very basic webpack build process, would help us modularise the frontend files

**Comment by andrewMacmurray** [comment]
links #48

**Comment by nelsonic** [comment]
Limited benefit at this stage. this whole app can be build with *one JS* and *one CSS* file. 
when you feel _pain_ of having "_too many_" frontend files, let us know.

**Comment by andrewMacmurray** [comment]
@nelsonic I think I'm just missing requiring / importing files 😭 😆
