### ISSUE TITLE
Ids in client_actions

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#63]
The unique ids for client_actions could be made using the id and promptID in the `actions` section of the localStorage. Another option is to make the id in the actions section unique with the path from topic -> prompt -> action

e.g. 
```
{ actions: [
    {
      id: 111,
      value: '1st Action',
      promptID: 1
    }
  ]
}
```

**Comment by nelsonic** [comment]
@katbow the implication here is that _several_ actions will be created on the client while _offline_?
will the `id` for each person be generated on the server? do `client_actions` need to be _globally_ unique or just _unique_ per `person` ("user") ?

**Comment by andrewMacmurray** [comment]
@nelsonic I think they just have to be unique per `person` as we're assuming that each companion will be able to edit their own prompts / actions (i.e. if they have some specific local knowledge they can adjust their own prompts / actions accordingly) so effectively each full set of prompts / actions is tied to only one user

**Comment by andrewMacmurray** [comment]
closing as we're going to be adding these on the frontend (either via reselect or our own functions)
will write up in the data requirements wiki https://github.com/ageuk/companion-app/wiki/Data-requirements-(online-and-offline-use)
