### ISSUE TITLE
Companion-specific actions

### ISSUE THREAD

**Issue by rjmk** [ageuk/companion-app#65]
Our data structure as it currently stands is insufficient to associate a prompt-action with a specific companion. It is sufficient to associate it to a single client *if* the action sits under a custom topic (and custom topics are associated with a single client)

Exactly how we extend the current schema depends on the desired functionality. Questions we need to answer include

(1) Can multiple companions share custom actions?
(2) Can a companion link a custom action to a specific client?
(3) Can a companion delete questions?

We probably don't want to add this functionality in the next few sprints, but it will be worth tweaking the data structure so any necessary actions can be easily supported.

cc/ @katbow @andrewMacmurray

**Comment by katbow** [comment]
@rjmk this is something we'll be starting to look at for this sprint, mainly involving how we can connect actions that are added to the to-do list with a specific companion and client. 

The relevant questions for what we need to complete this sprint is 1 and 2.
The actions will be customised at the local ageuk level i.e. if there are 3 companions testing out the application in Coventry, all three of these companions will have the same customised topics, prompts, and actions (which means the answer to the second question is no).

We aren't adding in customisation for this sprint, however we are linking up the action to do list so this might be something to keep in mind. The other half of this which is important for this sprint is in #77

**Comment by iteles** [comment]
Definitely needs to be kept in mind - issues are #21 and #23

**Comment by andrewMacmurray** [comment]
@iteles we had a talk with @rjmk about this yesterday, the initial thought was to have an extra location / area field in topics / prompts / actions that would let us localise these to an area like Coventry or Faversham.
