### ISSUE TITLE
Accessing local storage when connected to add to MySQL

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#68]
Need more research on:

- [ ] encrypting client data in local storage

- [ ] Accessing local storage data when connected to internet and putting in db

**Comment by iteles** [comment]
@katbow Is this a technical task of #32?

**Comment by andrewMacmurray** [comment]
@iteles yes it is 👍

**Comment by katbow** [comment]
closing - broken down into #79, #80, #81
