### ISSUE TITLE
Open a prompt to see a list of possible actions

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#7]
As a companion I would like to be able to select a prompt so that I can choose an action from a list.

**Comment by iteles** [comment]
comment **example**

- bullet point example
  - sub-bullet


<img width="1262" alt="screen shot 2016-06-27 at 22 13 01" src="https://cloud.githubusercontent.com/assets/4185328/16412967/f40bf9ce-3d26-11e6-92b1-fb48950f133e.png">
