### ISSUE TITLE
Fitting to the style guidelines

### ISSUE THREAD

**Issue by asmaasehli** [ageuk/companion-app#76]
I would like this App to be in line with our Brand Guidelines and online Styleguide so that it is clear it's an Age UK product.

Colour changes. Please change the following:
- Dark blue = #006EA1
- Purple = #724B89
- Pink = #85004F
- Green = #557D25 
- Sky Blue = #007AB2
- Orange = #CD4C10

These are our colours from the digital styleguide.

Font needs to FSMe across the board (with the correct weighting at each level)

Logo is incorrect - needs to be as attached please (with 'Love later life' strapline).

![age uk lll logo rgb](https://cloud.githubusercontent.com/assets/20186112/16770363/8ba5065e-4844-11e6-88ac-3e6cf5081b0f.jpg)

**Comment by andrewMacmurray** [comment]
@asmaasehli ok can update the colours.

We'll most likely get the font working a bit later (once we've got all the resources etc)

Just a thought with the logo though, the tagline will probably look really small, is it essential?

**Comment by asmaasehli** [comment]
Yep - regardless if it's tiny it's the only logo we're allowed to use @andrewMacmurray

**Comment by andrewMacmurray** [comment]
@asmaasehli 👍

**Comment by asmaasehli** [comment]
Ohhh I don't know how to do emotions @andrewMacmurray ... I was going to hashtag #branding ... but I don't know if hashtags are still cool?

**Comment by andrewMacmurray** [comment]
😆 if you type `:` you get some emoji prompts

here's the full list http://www.emoji-cheat-sheet.com/ ✨ 🎉 😄

**Comment by andrewMacmurray** [comment]
@rikardoH do you think it would be ok to include the font css in the repo? Was just thinking it's going to be visible anyway by anyone who uses a browser inspector

**Comment by rikardoH** [comment]
@andrewMacmurray Yep, that's fine. As you say, it's accessible on the main Age UK site as-is anyway.

**Comment by andrewMacmurray** [comment]
Thanks @rikardoH, will add that in today

**Comment by andrewMacmurray** [comment]
closed with pr #127
