### ISSUE TITLE
Topics for Rafe 

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#77]
:registered: @rjmk 

What we wanted to discuss in our hangout tomorrow (or skype!) mainly revolves around how we can change our data structure around for the actions to do list.

Currently the client_actions in localStorage doesn't connect together which prompt/topic the action is from. It currently contains the id, client_id and action_id. We were thinking about how we connect in the prompt and topic ids. We considered if we should be adding in the topicID in the actions section as well, or if there was another way to do this.

This relates to the issues we were discussing in #63.

**Comment by andrewMacmurray** [comment]
The upshot of this was to make all the changes to the data on the frontend (so the sql structure is preserved) but transform it into a more render friendly version (will be updating the wiki with this structure...)

**Comment by andrewMacmurray** [comment]
now as a section in the wiki https://github.com/ageuk/companion-app/wiki/Rafe's-Pearls-of-Wizdom
