### ISSUE TITLE
Local storage spike

### ISSUE THREAD

**Issue by katbow** [ageuk/companion-app#9]
Research local storage for making the app function offline

**Comment by andrewMacmurray** [comment]
@nelsonic @iteles @rjmk We've been doing some research on some methods to make the app work offline, we've written them up in the wiki

https://github.com/ageuk/companion-app/wiki/Taking-the-App-Offline

Any thoughts on this would be much appreciated 😄

**Comment by rjmk** [comment]
@andrewMacmurray Looks really great. Will try and make some more detailed comments soon

**Comment by andrewMacmurray** [comment]
Closing as have completed this research and talked to both @nelsonic and @rjmk about making the app function offline

**Comment by rjmk** [comment]
@andrewMacmurray Good to writeup / point people towards documentation of the final decision

**Comment by andrewMacmurray** [comment]
thanks @rjmk will write up the changes in the wiki

**Comment by andrewMacmurray** [comment]
Our docs for taking the app offline
https://github.com/ageuk/companion-app/wiki/Taking-the-App-Offline
